title: Rommel Labastida # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I have over 12 years of experience in collecting, warehousing, analysing, and managing all sorts of data. 
  <br><br>
  I make full use of my programming skills to automate ETL for consistently accurate source for dashboards/reports and analysis as I believe data insights are only as accurate as the quality of the source data.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>
  <br><br>
  
  
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
